import base64, sys

chunks = []
def add_chunk(b64text):
    chunks.append(base64.b64decode(b64text).decode('utf-8'))
add_chunk('aW1wb3J0IG9zLCBqc29uLCByZSwgdGhyZWFkaW5nLCBkYXRldGltZSwgbG9nZ2luZwppbXBvcnQgdXJsbGliLnJlcXVlc3QsIHVybGxpYi5lcnJvcgpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKZnJvbSBmYXN0YXBpIGltcG9ydCBGYXN0QVBJLCBSZXF1ZXN0CmZyb20gZmFzdGFwaS5yZXNwb25zZXMgaW1wb3J0IEhUTUxSZXNwb25zZSwgSlNPTlJlc3BvbnNlCmZyb20gZmFzdGFwaS5zdGF0aWNmaWxlcyBpbXBvcnQgU3RhdGljRmlsZXMKZnJvbSBweWRhbnRpYyBpbXBvcnQgQmFzZU1vZGVsCmZyb20gdHlwaW5nIGltcG9ydCBPcHRpb25hbAppbXBvcnQgdXZpY29ybgoK')
